# Simple workflow for deploying to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check docker
        run: |
          docker info
          docker buildx ls
      - name: Build web_build
        run: make --directory=ci web_build
      - name: Build web_export
        run: make --directory=ci web_export
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist
  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
